[phases.setup]
nixPkgs = ["nodejs_18"]
cmds = ["npm install -g corepack@0.24.1", "corepack enable"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
